### PR TITLE
Check the files and author tags

### PR DESCRIPTION
**Pull request by theodorekwok**
Did a quick run through of code and made sure the code quality and styles are followed. Also added some tags for some methods which I think yall did

### CODE REVIEW

**Review by KVignesh122 — APPROVED** [review]
LGTM!

**Review by kum-wh — APPROVED** [review]

**Comment by williamlamjy** [comment]
refactor all methods with remarks from remark to remarks especially in AddXYZCommand and AddXYZParser

**Comment by williamlamjy** [comment]
refactor all methods containing pastReturn to pastReturns as well in the Etf classes

**Comment by williamlamjy** [comment]
in the different sub instrument need to refactor remark to remarks too

**Comment by williamlamjy** [comment]
LGTM

**Pull request merged**
